name: Create a Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on tags like v1.0.0, v2.1.3, etc.
    branches:
      - "*"

permissions:
  contents: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        id: create_release
        run: |
          gh release create ${{ github.ref_name }} --title \
          --title "${{ github.ref_name }}" \
          --notes "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-majorver:
    name: Update Major Version
    runs-on: ubuntu-latest
    needs: create-release
    permissions:
      contents: write

    steps:
      - name: Update Major Version Tag
        uses: nowactions/update-majorver@v1
